# Documentation: https://hub.docker.com/_/mongo/
# TODO: Configure where database is to be stored
# WiredTiger is the default storage engine starting in 3.2
# Compression is enabled by default when using WiredTiger
FROM openfrontier/gerrit:latest
